export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_DET_REQUEST = 'GET_DET_REQUEST';
export const GET_DET_FAILURE = 'GET_DET_FAILURE';
export const GET_DET_SUCCESS = 'GET_DET_SUCCESS';